name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: True
