name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        id: semver_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Print versioning
        run: |
          echo "Version Info:"
          echo "  Previous ${{ steps.semver_tag.outputs.previous_tag }}"
          echo "  Release ${{ steps.semver_tag.outputs.new_tag }}"
          
      - name: Update VERSION.txt
        run: |
          echo "Writing new version (${{ steps.semver_tag.outputs.new_version }}) to VERSION.txt..."
          echo "${{ steps.semver_tag.outputs.new_version }}" >> VERSION.txt
          
      - name: Update Changelog.txt
        run: |
          echo "${{ steps.semver_tag.outputs.changelog }}" >> changelog.txt
         
      - name: Commit and push version changes in files 
        uses: actions-x/commit@v2
        with:
          branch: main
          message: "ci: Version update ${{ steps.semver_tag.outputs.new_tag }}"
          
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.semver_tag.outputs.changelog }}
          tag: ${{ steps.semver_tag.outputs.new_tag }}
          generateReleaseNotes: True
