name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update VERSION.txt
        run: |
          echo "Writing new version (${{ steps.semver_tag.outputs.new_version }}) to VERSION.txt..."
          echo "${{ steps.semver_tag.outputs.new_version }}\n" > VERSION.txt
          
      - name: Update changelog.txt
        run: |
          echo "${{ steps.semver_tag.outputs.changelog }}" >> changelog.txt
         
      - name: Commit and push version changes in files 
        uses: actions-x/commit@v2
        with:
          branch: main
          message: "ci: Version ${{ steps.semver_tag.outputs.new_tag }}"
          
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.semver_tag.outputs.new_version }}
          body: ${{ steps.semver_tag.outputs.changelog }}
          tag: ${{ steps.semver_tag.outputs.new_tag }}
          generateReleaseNotes: True
